### ISSUE TITLE
Specify an array of targets in the build section

### ISSUE THREAD

**Issue by giraffekey** [camchenry/boon#17]
It would be nice to have something like this:
```
[build]
target = ["windows", "macos"]
```
And also an option for
```
target = "all"
```
The advantage here is that you can just run `boon build .` without having to specify a target each time. It is also more flexible as you can choose exactly which targets to build for, which could be helpful when there is more than just two possible ones. Also, it may be a good idea to split the "windows" target into "win32" and "win64".

**Comment by giraffekey** [comment]
I'm currently working on implementing this. I won't split up "windows" without feedback on that suggestion and there won't be support for specifying multiple targets with the `--target` flag.

**Comment by camchenry** [comment]
Closed by #18.
