### ISSUE TITLE
Require failed

### ISSUE THREAD

**Issue by ValentinChCloud** [camchenry/boon#2]
Hello, 
When I package my game with boon, all my requires failed when I run my  game.love :
![image](https://user-images.githubusercontent.com/26431997/56867701-a7335880-69e8-11e9-980b-5e146ac5cf5b.png)

```lua
my_lib = require("lib.mon")
```

**Comment by camchenry** [comment]
Thanks for reporting this. Any chance that you could attach the packaged game and/or the source code? That would help me figure this out.

**Comment by ValentinChCloud** [comment]
I'm wondering, boon download his own love version, it can't  use the present one on my machine?
[cave_generator.zip](https://github.com/camchenry/boon/files/3126806/cave_generator.zip)

**Comment by camchenry** [comment]
I apologize for the long wait time, but I looked at your file and noticed it was zipping with backslashes in it. I pushed an update which may fix the issue for you? Please try it out if you are able.
