### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by chrsm** [camchenry/boon#24]
Hi all!

Thanks for boon - it's.. been a boon to my workflow.

I've been building it from source from the time that LOVE moved to GitHub, as the '20 release is still using the old bitbucket URLs. However, I'd like to remove that step from my CI pipeline and be able to download the binary if possible.

Any chance we could get a new GitHub release to facilitate that?

**Comment by camchenry** [comment]
@chrsm I just published a new version: 0.3.0. Let me know if you have any issues. Thanks!

**Comment by chrsm** [comment]
Thank you @camchenry :D
