### ISSUE TITLE
Missing support for Love2D 11.4 and 11.5

### ISSUE THREAD

**Issue by gingerbeardman** [camchenry/boon#32]
Problem seems twofold:
1. latest macOS release build is so old it only has 11.3 in it
2. latest source is not aware of 11.5

```
% boon love download 11.5
error: '11.5' isn't a valid value for '<version>'
	[possible values: 0.10.2, 11.0, 11.1, 11.2, 11.3]

	Did you mean '11.3'?

USAGE:
    boon love download <version>

For more information try --help
```

**Comment by gingerbeardman** [comment]
11.5 added in #33

**Comment by camchenry** [comment]
Thanks for reporting this! I'll take a look at your pull request when I have a chance. I greatly appreciate the contribution.

**Comment by camchenry** [comment]
Closed by https://github.com/camchenry/boon/pull/33
